# Generated by Django 3.1.8 on 2021-08-19 21:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0002_remove_user_registration_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClothingItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='StandardBox',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Subscription',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.AddField(
            model_name='user',
            name='bonus_item',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='service.clothingitem'),
        ),
        migrations.AddField(
            model_name='user',
            name='standard_box',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='service.standardbox'),
        ),
        migrations.AddField(
            model_name='user',
            name='subscription_type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='service.subscription'),
        ),
    ]
