# Generated by Django 3.1.8 on 2021-08-19 21:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0003_auto_20210819_2117'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='start_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
