# Generated by Django 3.1.8 on 2021-08-19 21:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0004_auto_20210819_2119'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='is_employee',
            field=models.BooleanField(null=True),
        ),
    ]
